apiVersion: v1
kind: Secret
metadata:
  name: fullstack-chatapp-secret
  namespace: chat-app
type: Opaque
stringData:
  JWT_SECRET: "VWFldjhjUDNscFZPZXFZSkZWdXBoM1dhZXVlT1ptc09uOEsyMHdXMVdYVA=="
  uri: mongodb://admin:production@mongodb:27017/chat-app?authSource=admin
  NODE_ENV: "production"
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "production"
  MONGO_DB: "chat-app"
  MONGO_HOST: "mongodb"
  MONGO_PORT: "27017"